version: "3"
services:
   config-server:
      build:
         config-server
      deploy:
         resources:
            limits:
               cpus: '0.5'
               memory: 300M
            reservations:
               cpus: '0.3'
               memory: 250M
      ports:
         - 8888:8888             
   sensor-emails-provider:
      build:
         sensorEmailsProvider
      deploy:
         resources:
            limits:
               cpus: '0.5'
               memory: 300M
            reservations:
               cpus: '0.3'
               memory: 250M 
      environment:
         - MONGO_PASSWORD=${MONGO_PASSWORD}
      ports:
         - 8686:8686         
   sensor-range-provider:
      build:
         sensorRangeProvider
      deploy:
         resources:
            limits:
               cpus: '0.5'
               memory: 300M
            reservations:
               cpus: '0.3'
               memory: 250M 
      environment:
         - MONGO_PASSWORD=${MONGO_PASSWORD}      
   admin-console:
      build:
         admin-console
      deploy:
         resources:
            limits:
               cpus: '0.5'
               memory: 300M
            reservations:
               cpus: '0.3'
               memory: 250M
      environment:
         - MONGO_PASSWORD=${MONGO_PASSWORD}
         - KAFKA_API_SECRET=${KAFKA_API_SECRET}
      ports:
      - 8787:8787
   analyzer:
      build:
         analyzer
      deploy:
         resources:
            limits:
               cpus: '0.5'
               memory: 300M
            reservations:
               cpus: '0.3'
               memory: 250M
      environment:
         - KAFKA_API_SECRET=${KAFKA_API_SECRET}
   avg-populator:
      build:
         avg-populator
      deploy:
         resources:
            limits:
               cpus: '0.5'
               memory: 300M
            reservations:
               cpus: '0.3'
               memory: 250M
      environment:
         - MONGO_PASSWORD=${MONGO_PASSWORD}
         - KAFKA_API_SECRET=${KAFKA_API_SECRET}
   avg-reducer:
      build:
         avg-reducer
      deploy:
         resources:
            limits:
               cpus: '0.5'
               memory: 300M
            reservations:
               cpus: '0.3'
               memory: 250M
      environment:
         - KAFKA_API_SECRET=${KAFKA_API_SECRET}
         - REDIS_PASSWORD=${REDIS_PASSWORD}
   email-notifier:
      build:
         email-notifier
      deploy:
         resources:
            limits:
               cpus: '0.5'
               memory: 300M
            reservations:
               cpus: '0.3'
               memory: 250M
      environment:
         - KAFKA_API_SECRET=${KAFKA_API_SECRET}
         - MAIL_PASSWORD=${MAIL_PASSWORD}
         - ACC_NAME=${ACC_NAME}